### ISSUE TITLE
Is this support RTL ?

### ISSUE THREAD

**Issue by ramkgunturu** [curtx/react-native-swipe-tabs#1] opened 2021-09-06 07:11 UTC
Is this support RTL ?

**Comment by curtx** [comment] 2021-09-06 07:25
Yes, it does support RTL. If you need assistance, I can help.

**Comment by ramkgunturu** [comment] 2021-09-06 07:46
Thanks a lot

**Comment by curtx** [comment] 2021-09-06 07:52
Thank you! for reaching out. Would you like to close this issue?

**Comment by ramkgunturu** [comment] 2021-09-06 08:17
I just tried with small example its not working with dynamic tabs and also Tabs are not showing as expect.

RTL it changing but when we swipe nothing is displaying there

**Comment by ramkgunturu** [comment] 2021-09-06 08:19
```
import React, { Component, useState } from "react";
import { View, Text, TextInput,18nManager } from "react-native";
import SwipeableTabs from "react-native-swipe-tabs";

// I18nManager.forceRTL(false);

function Home1() {
  return (
    <View>
      <Text>Home1</Text>
    </View>
  );
}
function Home2() {
  return (
    <View>
      <Text>Home2</Text>
    </View>
  );
}
function Home3() {
  return (
    <View>
      <Text>Home3</Text>
    </View>
  );
}
export default class Home extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selectedIndex: 0,
    };
  }

  render() {
    return (
      <SwipeableTabs
        onSwipe={(x) => this.setState({ selectedIndex: x })}
        selectedIndex={this.state.selectedIndex}
      >
        <Home1 />
        <Home2 />
        <Home3 />
      </SwipeableTabs>
    );
  }
}

```

**Comment by curtx** [comment] 2021-09-06 08:53
Thank-you for providing your code. Sorry for the inconvenience. Can you please install with latest version 1.0.6 and check, if it works properly. Also refresh the app when you change RTL flag.

**Comment by curtx** [comment] 2021-09-10 04:50
@ramkgunturu  I have put the fix in my latest version. You have not replied me, whether it addressed your problem or not? If still there is an issue please reply here, within next 2 days. Otherwise, I will have to mark this issue as closed. Thank-you!

**Comment by curtx** [comment] 2021-09-13 03:30
I believe the issue is resolved. You can reopen it if you want.

**Closed as completed by curtx** 2021-09-13 03:30 UTC
Labels: good first issue, question
